### ISSUE TITLE
Create backup of Collector DB

### ISSUE THREAD

**Issue by isaacjwilliams** [wfth/collector#14]

**Comment by isaacjwilliams** [comment]
We can create a dump file (contains steps to return to the state of the database when `pg_dump` was run) and save it to Dropbox.

`pg_dump collector > ~/Dropbox/collector_dump.txt`

Then, when worst comes to worst, we can restore the database pretty easily.

`psql collector < ~/Dropbox/collector_dump.txt`

[Docs!](https://www.postgresql.org/docs/9.5/static/backup-dump.html)

**Comment by aiwilliams** [comment]
Use `pg_dump -Ox` to avoid references to users.

**Comment by aiwilliams** [comment]
There are now instructions in the converter app for uploading the backup to Heroku. https://wo-ex-stage.herokuapp.com is listing all the production content now!
